### ISSUE TITLE
ERROR: Referenced sniff "SlevomatCodingStandard.Namespaces.UseFromSameNamespace" does not exist

### ISSUE THREAD

**Issue by panosru** [spryker/code-sniffer#154] opened 2019-02-18 09:47 UTC
I'm getting the errors you see in issue title when I try to run `phpcs --standard=vendor/spryker/code-sniffer/Spryker/ruleset.xml ./src`

![image](https://user-images.githubusercontent.com/400362/52942066-e606bb80-3372-11e9-99af-a2512a0b318f.png)

Thanks!

**Comment by dereuromark** [comment] 2019-02-18 10:00
Interesting.
Sounds like it cannot resolve the referenced link to the other sniff then. Maybe it needs to be absolute or sth? Did you check what works here?

Tip:
You could use your own project ruleset and only refer to the core one, as seen in https://github.com/spryker-shop/suite/blob/master/config/ruleset.xml#L10
That should have the paths always working.

**Comment by panosru** [comment] 2019-02-18 10:07
@dereuromark 

I also tried an absolute path from the global install

```
phpcs --standard=/Users/***/.composer/vendor/spryker/code-sniffer/Spryker/ruleset.xml ./src
ERROR: Referenced sniff "SlevomatCodingStandard.Namespaces.UseFromSameNamespace" does not exist

Run "phpcs --help" for usage information
```

Then I added a `ruleset.xml` file in my project but...
![image](https://user-images.githubusercontent.com/400362/52943357-9aa1dc80-3375-11e9-902f-515df6670173.png)

same issue as you can see...

My `phpcs` version is `3.4.0`

```
$ phpcs --version
PHP_CodeSniffer version 3.4.0 (stable) by Squiz (http://www.squiz.net)
```

**Comment by dereuromark** [comment] 2019-02-18 10:24
Did you try the linked version?

    <rule ref="vendor/spryker/code-sniffer/Spryker/ruleset.xml"/>

inside your local one?

**Comment by panosru** [comment] 2019-02-18 10:27
@dereuromark yes, same result...

**Comment by dereuromark** [comment] 2019-02-18 10:29
For us it works, makes me think something went wrong with your autoloader classmap maybe?
As this seems to be specific to your env.
See also all tests passing using the same kind of reference.

**Comment by panosru** [comment] 2019-02-18 10:31
Well, I just followed the instructions, install the package, added the `ruleset.xml` file, and run `phpcs` as described in manual...

**Comment by dereuromark** [comment] 2019-02-18 10:32
It looks like you are not running it as expected or documented.
The way you execute it you seem to be in the wrong path.
Are you running it from the root project dir? The one that has the composer.json you have been checking out? Otherwise, the path map would not be valid.

**Comment by panosru** [comment] 2019-02-18 10:38
@dereuromark indeed running `$ ./vendor/bin/phpcs` instead of `$ phpcs` worked... 

I'm used to having all my dev tools in global space rather than local, it would be nice to be able to run it from global space instead of installing it in each project I work on.

Thanks!

**Comment by dereuromark** [comment] 2019-02-18 11:08
If you figure that out you can PR a suggested improvement.
For now please respect the standard documentation and always find your path to root and execute from there as intended for it to work.

You can always do this in tooling:

    cd path/to/root && vendor/bin/...

That chaining is also how we do things where needed. 
Closing then as invalid. Documentation is clear on the usage.

**Closed by dereuromark** 2019-02-18 11:08 UTC
