### ISSUE TITLE
Problem with multiple lines in the end of file

### ISSUE THREAD

**Issue by Ole-Gi** [spryker/code-sniffer#88] opened 2017-08-18 09:15 UTC
Code sniff fails if after any class we add 2 empty lines (or more)

```
............................................................ 1380 / 2092 (66%)
..........................................PHP Notice:  Undefined offset: 537 in /data/shop/development/current/vendor/squizlabs/php_codesniffer/CodeSniffer/File.php on line 826
PHP Stack trace:
PHP   1. {main}() /data/shop/development/current/vendor/squizlabs/php_codesniffer/scripts/phpcs:0
PHP   2. PHP_CodeSniffer_CLI->runphpcs() /data/shop/development/current/vendor/squizlabs/php_codesniffer/scripts/phpcs:25
PHP   3. PHP_CodeSniffer_CLI->process() /data/shop/development/current/vendor/squizlabs/php_codesniffer/CodeSniffer/CLI.php:113
PHP   4. PHP_CodeSniffer->processFiles() /data/shop/development/current/vendor/squizlabs/php_codesniffer/CodeSniffer/CLI.php:998
PHP   5. PHP_CodeSniffer->processFile() /data/shop/development/current/vendor/squizlabs/php_codesniffer/CodeSniffer.php:653
PHP   6. PHP_CodeSniffer->_processFile() /data/shop/development/current/vendor/squizlabs/php_codesniffer/CodeSniffer.php:1772
PHP   7. PHP_CodeSniffer_File->start() /data/shop/development/current/vendor/squizlabs/php_codesniffer/CodeSniffer.php:1894
PHP   8. Spryker\Sniffs\WhiteSpace\EmptyLinesSniff->process() /data/shop/development/current/vendor/squizlabs/php_codesniffer/CodeSniffer/File.php:576
PHP   9. Spryker\Sniffs\WhiteSpace\EmptyLinesSniff->assertMaximumOneEmptyLineBetweenContent() /data/shop/development/current/vendor/spryker/code-sniffer/Spryker/Sniffs/Whitespace/EmptyLinesSniff.php:40
PHP  10. PHP_CodeSniffer_File->addFixableError() /data/shop/development/current/vendor/spryker/code-sniffer/Spryker/Sniffs/Whitespace/EmptyLinesSniff.php:60
PHP  11. PHP_CodeSniffer_File->addError() /data/shop/development/current/vendor/squizlabs/php_codesniffer/CodeSniffer/File.php:938
PHP Notice:  Undefined offset: 537 in /data/shop/development/current/vendor/squizlabs/php_codesniffer/CodeSniffer/File.php on line 827
PHP Stack trace:
PHP   1. {main}() /data/shop/development/current/vendor/squizlabs/php_codesniffer/scripts/phpcs:0
PHP   2. PHP_CodeSniffer_CLI->runphpcs() /data/shop/development/current/vendor/squizlabs/php_codesniffer/scripts/phpcs:25
PHP   3. PHP_CodeSniffer_CLI->process() /data/shop/development/current/vendor/squizlabs/php_codesniffer/CodeSniffer/CLI.php:113
PHP   4. PHP_CodeSniffer->processFiles() /data/shop/development/current/vendor/squizlabs/php_codesniffer/CodeSniffer/CLI.php:998
PHP   5. PHP_CodeSniffer->processFile() /data/shop/development/current/vendor/squizlabs/php_codesniffer/CodeSniffer.php:653
PHP   6. PHP_CodeSniffer->_processFile() /data/shop/development/current/vendor/squizlabs/php_codesniffer/CodeSniffer.php:1772
PHP   7. PHP_CodeSniffer_File->start() /data/shop/development/current/vendor/squizlabs/php_codesniffer/CodeSniffer.php:1894
PHP   8. Spryker\Sniffs\WhiteSpace\EmptyLinesSniff->process() /data/shop/development/current/vendor/squizlabs/php_codesniffer/CodeSniffer/File.php:576
PHP   9. Spryker\Sniffs\WhiteSpace\EmptyLinesSniff->assertMaximumOneEmptyLineBetweenContent() /data/shop/development/current/vendor/spryker/code-sniffer/Spryker/Sniffs/Whitespace/EmptyLinesSniff.php:40
PHP  10. PHP_CodeSniffer_File->addFixableError() /data/shop/development/current/vendor/spryker/code-sniffer/Spryker/Sniffs/Whitespace/EmptyLinesSniff.php:60
PHP  11. PHP_CodeSniffer_File->addError() /data/shop/development/current/vendor/squizlabs/php_codesniffer/CodeSniffer/File.php:938
E................. 1440 / 2092 (69%)
............................................................ 1500 / 2092 (72%)
............................................................ 1560 / 2092 (75%)
```

**Comment by dereuromark** [comment] 2017-08-18 13:05
I cannot reproduce this using our dev-master.
Can you please confirm that this fixes things?
Then we can tag a new release here today.

**Comment by dereuromark** [comment] 2017-08-18 13:09
Fixed with https://github.com/spryker/code-sniffer/commit/d952b05f9093e0e57db9c99ecf36d115fc579665

**Closed by dereuromark** 2017-08-18 13:09 UTC
Labels: bug, prio
